apps/front/models.py
from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
import shortuuid
import enum


class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UKNOW = 4


class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100), primary_key=True, default=shortuuid.uuid)
    telephone = db.Column(db.String(50), nullable=False, unique=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.UKNOW)
    join_time = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        if "password" in kwargs:
            self.password = kwargs.get("password")
            kwargs.pop("password")
            super(FrontUser, self).__init__(*args, **kwargs)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self, rawpwd):
        result = check_password_hash(self._password, rawpwd)
        return result

apps/front/forms.py
from apps.forms import BaseForm
from wtforms import StringField, IntegerField
from wtforms.validators import Regexp, EqualTo, ValidationError, InputRequired
from utils import zlcache


class SignupForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码！')])
    sms_captcha = StringField(validators=[Regexp(r"\w{4}", message='请输入正确格式的短信验证码！')])
    username = StringField(validators=[Regexp(r".{2,20}", message='请输入正确格式的用户名！')])
    password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    password2 = StringField(validators=[EqualTo("password1", message='两次输入的密码不一致！')])
    graph_captcha = StringField(validators=[Regexp(r"\w{4}", message='请输入正确格式的短信验证码！')])

    def validate_sms_captcha(self, field):
        sms_captcha = field.data
        telephone = self.telephone.data
        sms_captcha_mem = zlcache.get(telephone)
        if not sms_captcha_mem or sms_captcha_mem.lower() != sms_captcha.lower():
            raise ValidationError(message='短信验证码错误！')

    def validate_graph_captcha(self, field):
        graph_captcha = field.data
        graph_captcha_mem = zlcache.get(graph_captcha.lower())
        if not graph_captcha_mem:
            raise ValidationError(message='图形验证码错误！')


class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码！')])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    remeber = StringField()


class ApostForm(BaseForm):
    title = StringField(validators=[InputRequired(message='请输入标题！')])
    content = StringField(validators=[InputRequired(message='请输入内容！')])
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id！')])


class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入内容！')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子ID')])

apps/common/views.py
import json

import qiniu
from flask import Blueprint, request, make_response, jsonify

from utils import restful, zlcache
from utils.alidayu import send_sms
from .forms import SmsCaptchaForm
from io import BytesIO
from utils.captcha import Captcha
from tasks import send_sms_captcha
bp = Blueprint("common", __name__, url_prefix="/c")


# @bp.route('/sms_captcha/', methods=['POST'])
# def sms_captcha():
#     form = SmsCaptchaForm(request.form)
#     if form.validate():
#         telephone = form.telephone.data
#         captcha = Captcha.gene_text(number=4)
#         template = {
#             'code': captcha
#         }
#         res = send_sms_captcha(template, telephone)
#         res_dict = json.loads(res)
#         if res_dict.get('Message') == 'OK' and res_dict.get('Code') == 'OK':
#             print("短信验证码是%s" % captcha)
#             zlcache.set(telephone, captcha)
#             return restful.success()
#         else:
#             return restful.server_error()
#     else:
#         return restful.params_error(form.get_error())


# @bp.route('/sms_captcha/', methods=['POST'])
# def sms_captcha():
#     telephone = request.form.get("telephone")
#     captcha = Captcha.gene_text(number=4)
#     template = {
#         'code': captcha
#     }
#     print(captcha)
#     res = send_sms_captcha(template, telephone)
#     res_dict = json.loads(res)
#     if res_dict.get('Message') == 'OK' and res_dict.get('Code') == 'OK':
#
#         print("短信验证码是%s" % captcha)
#         zlcache.set(telephone, captcha)
#         return restful.success()
#     else:
#         return restful.params_error()

@bp.route('/sms_captcha/', methods=['POST'])
def sms_captcha():
    form = SmsCaptchaForm(request.form)
    if form.validate():
        telephone = form.telephone.data
        captcha = Captcha.gene_text(number=4)
        template = {
            'code': captcha
        }
        print(captcha)
        zlcache.set(telephone, captcha)
        print(zlcache.get(telephone))
        res = send_sms(template, telephone)
        res_dict = json.loads(res)
        if res_dict.get('Message') == 'OK' and res_dict.get('Code') == 'OK':

            print("短信验证码是%s" % captcha)
            zlcache.set(telephone, captcha)
            return restful.success()
        else:
            return restful.params_error()
    else:
        return restful.params_error(form.get_error())

@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    zlcache.set(text.lower(), text.lower())
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


@bp.route('/uptoken/')
def uptoken():
    access_key = 'M4zCEW4f9XPanbMN-Lb9O0S8j893f0e1ezAohFVL'
    secret_key = '7BKV7HeEKM3NDJk8_l_C89JI3SMmeUlAIatzl9d4'
    q = qiniu.Auth(access_key, secret_key)

    bucket = 'hyvideo'
    token = q.upload_token(bucket)
    return jsonify({'uptoken': token})

apps/front/__init__.py
from .views import bp
from . import hooks

apps/front/views.py
from flask import Blueprint, views, render_template, request, session, url_for, g, abort
from .forms import SignupForm, SigninForm, ApostForm, AddCommentForm
from exts import db
from .models import FrontUser
from utils import restful, safeutils
import config
from ..models import BannerModel, BoardModel, PostModel, CommentModel, HighlightPostModel
from .decorators import login_required
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy import func

bp = Blueprint("front", __name__)


@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=0)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get('st', type=int, default=1)
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    posts = None
    total = 0
    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(), PostModel.create_time.desc())
    if board_id:
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total)
    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort
    }
    return render_template('front/front_index.html', **context)


@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)


@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/apost.html', boards=boards)
    else:
        form = ApostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


@bp.route('/acomments/', methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            return restful.success()
        else:
            return restful.params_error('帖子不存在')
    else:
        return restful.params_error(form.get_error())


class SignupView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(
                return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remeber = form.remeber.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remeber:
                    session.permanent = True
                    return restful.success()
            else:
                return restful.params_error(message='手机号或密码错误')
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

templates/front/apost.html
{% extends 'front/front_base.html' %}
{% from 'common/_macros.html' import static%}

{% block title %}
    发布帖子
{% endblock %}
{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static("front/js/front_apost.js") }}"></script>
{% endblock %}

{% block body %}
<form action="" method="post">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select name="board_id" class="form-control">
                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}

            </select>
        </div>
    </div>
    <div class="form-group">
        <script id="editor" type="text/plain"></script>
    </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
</form>
{% endblock %}

templates/front/front_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>知了课堂404</title>
</head>
<body>
  你要找的页面到火星去了~~
<div>
    <a href="/">回到首页</a>
</div>
</body>
</html>

templates/front/front_base.html
{% from 'common/_macros.html' import static%}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
    {% include "common/_heads.html" %}
    <link rel="stylesheet" href="{{ static('front/css/front_base.css') }}">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block head %}{% endblock %}
</head>
<body>
 <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">知了课堂Python论坛</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="请输入关键字">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            {% if g.front_user %}
                <span id="login-Tag" data-is-login="1" style="display: none"></span>
                <span id="login-tag" data-is-login="1" style="display:none;"></span>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="true">
                        {{ g.front_user.username }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#">个人中心</a></li>
                        <li><a href="#">设置</a></li>
                        <li><a href="#">注销</a></li>
                    </ul>
                </li>
            {% else %}
                <li><a href="{{ url_for('front.signin') }}">登录</a></li>
                <li><a href="{{ url_for("front.signup") }}">注册</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="main-container">
{% block body %}{% endblock %}
     </div>
</body>
</html>

templates/front/front_index.html
{% extends "front/front_base.html" %}
{% from "common/_macros.html" import static %}

{% block title %}知了课堂Python论坛{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static("front/css/front_index.css") }}">
{% endblock %}
{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel"
             data-interval="2000">
            <!-- 指示器 -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>

            <!-- 轮播图 -->
            <div class="carousel-inner" role="listbox">
                {% for banner in banners %}
                    {% if loop.first %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                <a href="{{ banner.link_url }}">
                    <img src="{{ banner.image_url }}" , alt="...">
                </a>
                </div>
                {% endfor %}
                </div>

                <!-- 左右切换的控制按钮 -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="post-group">
                <ul>
                    <ui class="post-group-head">
                             {% if current_sort == 1 %}
                    <li class="active"><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                {% else %}
                    <li><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                {% endif %}
                {% if current_sort == 2 %}
                    <li class="active"><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
                {% else %}
                    <li><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
                {% endif %}
                {% if current_sort == 3 %}
                    <li class="active"><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                {% else %}
                    <li><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                {% endif %}
                {% if current_sort == 4 %}
                    <li class="active"><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                {% else %}
                    <li><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                {% endif %}
                </ui>
                </ul>
                <ul class="post-list-group">
                    {% for post in posts %}
                        <li>
                            <div class="author-avatar-group">
                                <img src="{{ post.author.avatar or url_for('static',filename='common/images/logo.png') }}"
                                     alt="">
                            </div>
                            <div class="post-info-group">
                                <p class="post-title">
                                    <a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a>
                                    {% if post.highlight %}
                                        <span class="label label-danger">精华帖</span>
                                    {% endif %}
                                </p>
                                <p class="post-info">
                                    <span>作者:{{ post.author.username }}</span>
                                    <span>发表时间:{{ post.create_time }}</span>
                                    <span>评论:0</span>
                                    <span>阅读:0</span>
                                </p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {{ pagination.links }}
            </div>
        </div>
        <div class="sm-container">
            <div style="padding-bottom: 10px">
                <a href="{{ url_for('front.apost') }}" class="btn btn-warning btn-block">发布帖子</a>
            </div>
            <div class="list-group">
                {% if current_board==0 %}
                    <a href="/" class="list-group-item active">所有帖子</a>
                {% else %}
                    <a href="/" class="list-group-item">所有帖子</a>
                {% endif %}
                {% for board in boards %}
                    {% if board.id == current_board %}
                        <a href="{{ url_for('front.index', bd=board.id) }}" class="list-group-item active">{{ board.name }}</a>
                    {% else %}
                        <a href="{{ url_for('front.index', bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
{% endblock %}

templates/front/front_pdetail.html
{% extends 'front/front_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static('front/js/front_pdetail.js') }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_pdetail.css') }}">
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-container">
            <h2>{{ post.title}}</h2>
            <p class="post-info-group">
                <span>发表时间:{{ post.create_time }}</span>
                <span>作者:{{ post.author.username }}</span>
                <span>所属板块:{{ post.board.name }}</span>
                <span>阅读数:{{ post.read_count }}</span>
                <span>评论数:0</span>
            </p>
            <article class="post-content" id="post-content" data-id="{{ post.id }}">
                {{ post.content|safe }}
            </article>
        </div>
    <div class="comment-group">
        <h3>评论列表</h3>
        <ul class="comment-list-group">
            {% for comment in post.comments %}
            <li>
                <div class="avatar-group">
                    <img src="{{ comment.author.avatar or static('common/images/logo.png') }}">
                </div>
                <div class="comment-content">
                    <p class="author-info">
                        <span>{{ comment.author.username }}</span>
                        <span>{{ comment.create_time }}</span>
                    </p>
                    <p class="comment-txt">
                        {{ comment.content|safe }}
                    </p>
                </div>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div class="add-comment-group">
        <h3>发表评论</h3>
        <script id="editor" type="text/plain" style="height: 100px"></script>
        <div class="comment-btn-group">
            <button id="comment-btn" class="btn btn-primary">发表评论</button>
        </div>
    </div>
    </div>
    <div class="sm-container"></div>
{% endblock %}

templates/front/front_signin.html
{% from 'common/_macros.html' import static %}
{% extends 'front/signbase.html' %}
{% block title %}
    知了课堂登录
{% endblock %}
{% block head %}
    <script src="{{ static('front/js/front_signin.js') }}"></script>
{% endblock %}
{% block h2_title %}
    知了课堂账户登录
{% endblock %}
{% block sign_box %}
 <div class="form-group">
     <input type="text" class="form-control" name="telephone" placeholder="手机号码">
 </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密码">
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox", name="remeber", value="1">记住我
        </label>
    </div>
     <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
    </div>
    <div class="form-group">
        <a href="{{ url_for("front.signup") }}" class="signup-link">注册</a>
        <a href="#" class="resetpwd-link" style="float: right;">找回密码</a>
    </div>
{% endblock %}

templates/front/front_signup.html
{% from 'common/_macros.html' import static %}
{% extends 'front/signbase.html' %}
{% block title %}
    知了账户注册
{% endblock %}
{% block head %}
    <script src="{{ static('front/js/front_signup.js') }}"></script>
{% endblock %}
{% block h2_title %}
    知了课堂账户注册
{% endblock %}
{% block sign_box %}
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="telephone" placeholder="手机号码">
            <span class="input-group-btn">
                <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>
            </span>
        </div>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="用户名">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password1" placeholder="密码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="确认密码">
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
            <span class="input-group-addon captcha-addon">
                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">
            </span>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
    </div>
{% endblock %}

templates/front/signbase.html
{% from 'common/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
    <script src="{{ static('common/zlparam.js') }}"></script>
    <script src="{{ static('common/zlajax.js') }}"></script>
    <link rel="stylesheet" href="{{ static('common/sweetalert/sweetalert.css') }}">
    <script src="{{ static('common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ static('common/sweetalert/zlalert.js') }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_signbase.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<div class="out-box">
    <div class="logo-box">
        <a href="/">
            <img src="{{ static('common/images/logo.png') }}">
        </a>
    </div>
    <h2 class="page-title">{% block h2_title %}{% endblock %}</h2>
    <div class="sign-box">
         {% block sign_box %}{% endblock %}
    </div>
 <span style="display: none;" id="return_to_span">{{ return_to }}</span>
    </div>
</body>
</html>