apps/cms/forms.py
from wtforms import StringField, IntegerField
from wtforms.validators import Email, Length, InputRequired, EqualTo, ValidationError
from ..forms import BaseForm
from utils import zlcache
from flask import g


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='邮箱''格式不正确'),
                                    InputRequired(message='请输入邮箱')])
    password = StringField(validators=[Length(6, 20, message='密码格式不正确'),
                                       InputRequired(message='请输入密码')])
    remember = IntegerField()


class ResetPwdForm(BaseForm):
    oldpwd = StringField(validators=[Length(6, 20, message='请输入正确格式的旧密码')])
    newpwd = StringField(validators=[Length(6, 20, message='请输入正确格式的新密码')])
    newpwd2 = StringField(validators=[EqualTo("newpwd", message='确认密码必须和新密码保持一致')])


class ResetEmailForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确格式的邮箱')])
    captcha = StringField(validators=[Length(min=6, max=6, message='请输入正确格式的验证码')])

    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        captcha_cache = zlcache.get(email)
        if not captcha_cache or captcha.lower() != captcha_cache.lower():
            raise ValidationError('邮箱验证码错误！')

    def validate_email(self, field):
        email = field.data
        user = g.cms_user
        if user.email == email:
            raise ValidationError('不能修改为相同邮箱')


class AddBannersForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入名称')])
    image_url = StringField(validators=[InputRequired(message='请输入轮播图图片链接')])
    link_url = StringField(validators=[InputRequired(message='请输入轮播图跳转链接')])
    priority = IntegerField(validators=[InputRequired(message='请输入轮播图优先级')])


class UpdataBannersForm(AddBannersForm):
    banner_id = IntegerField(validators=[InputRequired(message='请输入轮播图id')])


class AddBoardForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入名称')])


class UpdateBoardForm(AddBoardForm):
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id')])

apps/cms/__init__.py
from .views import bp
import apps.cms.hooks

apps/cms/views.py
from flask import Blueprint, views, render_template, request, session, \
    redirect, url_for, g
from .forms import LoginForm, ResetPwdForm, ResetEmailForm, AddBannersForm, UpdataBannersForm, AddBoardForm, \
    UpdateBoardForm
from .models import CMSUser, CMSPersmission
from ..models import BannerModel, BoardModel, PostModel, HighlightPostModel
from .decorators import login_required, permission_required
import config
from exts import db, mail
from flask_mail import Message
from utils import restful, zlcache
import string
import random
from tasks import send_mail, send_sms_captcha

bp = Blueprint("cms", __name__, url_prefix="/cms")


@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')


@bp.route('/logout/')
@login_required
def logout():
    del session[config.CMS_USER_ID]
    return redirect(url_for('cms.login'))


@bp.route('/profile')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


@bp.route('/email_captcha/')
def email_captcha():
    # /email_capthca/?email=xxx@qq.com
    email = request.args.get('email')
    if not email:
        return restful.params_error('请传递邮箱参数！')

    # source.extend(["0","1","2","3","4","5","6","7","8","9"])
    source = list(string.ascii_letters)
    source.extend(map(lambda x: str(x), range(0, 10)))
    captcha = "".join(random.sample(source, 6))

    # # 给这个邮箱发送邮件
    # message = Message('Python论坛邮箱验证码', recipients=[email], body='您的验证码是：%s' % captcha)
    # try:
    #     mail.send(message)
    # except:
    #     return restful.server_error()
    send_mail.delay('Python论坛邮箱验证码', [email], '您的验证码是：%s' % captcha)
    zlcache.set(email, captcha)
    return restful.success()


@bp.route('/banners/')
@login_required
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/cms_banners.html', banners=banners)


@bp.route('/abanners/', methods=['POST'])
@login_required
def abanners():
    form = AddBannersForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/ubanners/', methods=['POST'])
@login_required
def ubanners():
    form = UpdataBannersForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner_id = form.banner_id.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个轮播图')
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dbanners/', methods=['POST'])
@login_required
def dbanners():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.params_error(message='请传入轮播图ID')
    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.params_error(message='没有这个轮播图')
    db.session.delete(banner)
    db.session.commit()
    return restful.success()


@bp.route('/posts/')
@login_required
@permission_required(CMSPersmission.POSTER)
def posts():
    post_list = PostModel.query.all()
    return render_template('cms/cms_posts.html', posts=post_list)


@bp.route('/hposts/', methods=['POST'])
@login_required
@permission_required(CMSPersmission.POSTER)
def hpost():
    post_id = request.form.get("post_id")
    if not post_id:
        return restful.params_error("请传入帖子ID")
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error("没有这篇帖子")
    highlight = HighlightPostModel()
    highlight.post = post
    db.session.add(highlight)
    return restful.success()


@bp.route('/uposts/', methods=['POST'])
@login_required
@permission_required(CMSPersmission.POSTER)
def upost():
    post_id = request.form.get("post_id")
    if not post_id:
        return restful.params_error("请传入帖子ID")
    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error("没有这篇帖子")
    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    return restful.success()


@bp.route('/comments/')
@login_required
@permission_required(CMSPersmission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


@bp.route('/boards/')
@login_required
@permission_required(CMSPersmission.BOARDER)
def boards():
    boards_model = BoardModel.query.all()
    return render_template('cms/cms_boards.html', boards=boards_model)


@bp.route('/aboard/', methods=['POST'])
@login_required
@permission_required(CMSPersmission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/uboard/', methods=['POST'])
@login_required
@permission_required(CMSPersmission.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board_id = form.board_id.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            return restful.success()
        else:
            return restful.params_error(message='没有这个板块')
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dboard/', methods=['POST'])
@login_required
@permission_required(CMSPersmission.BOARDER)
def dboard():
    board_id = request.form.get('board_id')
    if not board_id:
        return restful.params_error(message='请传入板块ID')
    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error(message='没有这个板块')
    db.session.delete(board)
    db.session.commit()
    return restful.success()


@bp.route('/fusers/')
@login_required
@permission_required(CMSPersmission.FORNTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')


@bp.route('/cusers/')
@login_required
@permission_required(CMSPersmission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


@bp.route('/croles/')
@login_required
@permission_required(CMSPersmission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')


class LoginView(views.MethodView):

    def get(self, message=None):
        return render_template('cms/cms_login.html', message=message)

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                if remember:
                    # 如果设置session.permanent = True
                    # 那么过期时间是31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='邮箱或密码错误')
        else:
            message = form.get_error()
            return self.get(message=message)


class ResetPwdView(views.MethodView):
    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        form = ResetPwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user

            if user.check_password(oldpwd):
                user.password = newpwd
                db.session.commit()
                return restful.success()
            else:

                return restful.params_error("旧密码错误")
        else:
            return restful.params_error(form.get_errors())


class ResetEmailView(views.MethodView):
    decoratirs = [login_required]

    def get(self):
        return render_template('cms/cms_resetemail.html')

    def post(self):
        form = ResetEmailForm(request.form)
        if form.validate():
            email = form.email.data
            g.cms_user.email = email
            return restful.success()
        else:
            return restful.params_error(form.get_error())


bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))
bp.add_url_rule('/resetpwd/', view_func=ResetPwdView.as_view('resetpwd'))
bp.add_url_rule('/resetemail/', view_func=ResetEmailView.as_view('resetemail'))

apps/front/views.py
from flask import Blueprint, views, render_template, request, session, url_for, g, abort
from .forms import SignupForm, SigninForm, ApostForm, AddCommentForm
from exts import db
from .models import FrontUser
from utils import restful, safeutils
import config
from ..models import BannerModel, BoardModel, PostModel, CommentModel, HighlightPostModel
from .decorators import login_required
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy import func

bp = Blueprint("front", __name__)


@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=0)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get('st', type=int, default=1)
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    posts = None
    total = 0
    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(), PostModel.create_time.desc())
    if board_id:
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total)
    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort
    }
    return render_template('front/front_index.html', **context)


@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)


@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/apost.html', boards=boards)
    else:
        form = ApostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


@bp.route('/acomments/', methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            return restful.success()
        else:
            return restful.params_error('帖子不存在')
    else:
        return restful.params_error(form.get_error())


class SignupView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(
                return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remeber = form.remeber.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remeber:
                    session.permanent = True
                    return restful.success()
            else:
                return restful.params_error(message='手机号或密码错误')
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}
{% block tittle %}
    轮播图管理
{% endblock %}
{% block head %}
    <script src="{{ static('cms/js/banners.js') }}"></script>
     <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{static('common/zlqiniu.js')}}"></script>
    <style>
        .top-box button{
            float: right;
        }
    </style>
{% endblock %}
{% block page_tittle %}
    {{ self.tittle() }}
{% endblock %}
{% block main_context %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
    </div>
    <table class="table table-bordered">
        <theard>
            <th>名称</th>
            <th>图片链接</th>
            <th>跳转链接</th>
            <th>优先级</th>
            <th>创建时间</th>
            <th>操作</th>
        </theard>
        <tbody>
            {% for banner in banners %}
                <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}" data-id="{{ banner.id }}">
                    <td>{{ banner.name }}</td>
                    <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                    <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.create_time }}</td>
                    <td><button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
<div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">添加轮播图</h4>
      </div>
      <div class="modal-body">
          <form action="" class="form-horizontal">
            <div class="form-group">
                <lable class="col-sm-2 control-label">名称:</lable>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                </div>
            </div>
                <div class="form-group">
                <lable class="col-sm-2 control-label">图片:</lable>
                <div class="col-sm-7">
                    <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                </div>
                    <button class="btn btn-info col-sm-2" id="upload-btn">添加图片:</button>
                </div>
                    <div class="form-group">
                <lable class="col-sm-2 control-label">跳转:</lable>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                </div>
                    </div>
                        <div class="form-group">
                <lable class="col-sm-2 control-label">权重:</lable>
                <div class="col-sm-10">
                    <input type="number" class="form-control" name="priority" placeholder="轮播图名称">
                </div>
            </div>
          </form>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

templates/cms/cms_base.html
{% from 'common/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block tittle %}{% endblock %}</title>
    {% include 'common/_heads.html' %}
    <link rel="stylesheet" href="{{ static('cms/css/cms_base.css') }}">
    <script src="{{ static('cms/js/cms_base.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">知了课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{url_for('cms.profile')}}">{{ g.cms_user.username }}</a></li>
            <li><a href="{{url_for('cms.logout')}}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{url_for('cms.profile')}}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                {% set cms_user = g.cms_user %}
               <li class="nav-group banners-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                  {% if cms_user.has_permission(CMSPersmission.POSTER) %}
                  <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                  {% endif %}
                  {% if cms_user.has_permission(CMSPersmission.COMMENTER) %}
                  <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                  {% endif %}
                  {% if cms_user.has_permission(CMSPersmission.BOARDER) %}
                 <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                  {% endif %}
              {% if cms_user.has_permission(CMSPersmission.FORNTUSER) %}
                 <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
                  {% endif %}
              {% if cms_user.has_permission(CMSPersmission.CMSUSER) %}
                 <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                  {% endif %}
              {% if cms_user.is_developer %}
                 <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>
                  {% endif %}
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_tittle %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_context %}{% endblock %}
            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}
{% block tittle %}板块管理{% endblock %}
{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{% endblock %}
{% block page_tittle %}
    {{ self.tittle()  }}
{% endblock %}
{% block main_context %}
    <div class="top-box">
        <button class="btn btn-warning" id="add-board-btn" style="float: right">添加新板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
                <th>板块名称</th>
            <th>帖子数量</th>
            <th>创建时间</th>
            <th>操作</th>
        </thead>
    <tbody>
        {% for board in boards %}
         <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
            <td>{{ board.name }}</td>
            <td>0</td>
            <td>{{ board.create_time }}</td>
            <td><button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}

{% block tittle %}评论管理{% endblock %}
{% block head %}

{% endblock %}
{% block page_tittle %}
    {{ self.tittle() }}
{% endblock %}
{% block main_context %}
    我是评论管理
{% endblock %}

templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}

{% block tittle %}组管理{% endblock %}
{% block head %}

{% endblock %}
{% block page_tittle %}
    {{ self.tittle() }}
{% endblock %}
{% block main_context %}
    我是组管理
{% endblock %}

templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}

{% block tittle %}后台用户管理{% endblock %}
{% block head %}

{% endblock %}
{% block page_tittle %}
    {{ self.tittle()  }}
{% endblock %}
{% block main_context %}
    我是后台用户管理
{% endblock %}

templates/cms/cms_fusers.html
{% extends 'cms/cms_base.html' %}

{% block tittle %}前台用户管理{% endblock %}
{% block head %}

{% endblock %}
{% block page_tittle %}
    {{ self.tittle()  }}
{% endblock %}
{% block main_context %}
    我是前台用户管理
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block tittle -%}
    cms管理系统
{%- endblock %}

{% block page_tittle -%}
    欢迎来到cms管理系统
{%- endblock %}

templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}
{% block tittle %}帖子管理{% endblock %}
{% block head %}
    <script src="{{ static('cms/js/posts.js') }}"></script>
{% endblock %}
{% block page_tittle %}
    {{ self.tittle() }}
{% endblock %}
{% block main_context %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>标题</th>
                <th>发布时间</th>
                <th>板块</th>
                <th>作者</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr data-id="{{ post.id }}" data-highlight="{{ post.highlight }}">
                    <td><a target="_blank" href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a></td>
                    <td>{{ post.create_time }}</td>
                    <td>{{ post.board.name }}</td>
                    <td>{{ post.author.username }}</td>
                    <td>
                        {% if post.highlight %}
                            <button class="btn btn-default btn-xs highlight-btn">取消加精</button>
                        {% else %}
                            <button class="btn btn-default btn-xs highlight-btn">加精</button>
                        {% endif %}
                        <button class="btn btn-danger btn-xs">移除</button>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/cms/cms_resetemail.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}
{% block tittle -%}
    修改邮箱
{%- endblock %}

{% block head %}
    <script src="{{ static('cms/js/resetemail.js') }}"></script>
{% endblock %}

{% block page_tittle -%}
    修改邮箱
{%- endblock %}

{% block main_context %}
    <form action="" method="post">
        <div class="form-container">
            <div class="form-group">
                <div class="input-group">
                    <input type="email" class="form-control" name="email" placeholder="请输入邮箱">
                    <scan class="input-group-addon" id="captcha-btn" style="cursor: pointer">获取验证码</scan>
                </div>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="captcha" placeholder="请输入验证码">
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="submit">立即修改</button>
            </div>
        </div>

    </form>
{% endblock %}